Update test_mac.yml

diff --git a/.github/workflows/test_mac.yml b/.github/workflows/test_mac.yml
--- a/.github/workflows/test_mac.yml
+++ b/.github/workflows/test_mac.yml
@@ -27,11 +27,8 @@ jobs:
         run: |
           mkdir -p ~/.docker/machine/cache
           curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.5/boot2docker.iso
-          while ! docker-machine create --driver xhyve default; do
-            docker-machine rm -f default
-            sleep 1;
-          done
-        
+          for i in $(seq 1 10); do docker-machine create --driver xhyve default && s=0 && break || sudo kill -9 `ps aux | grep xhyve | grep -v grep | awk '{print $2}'` && sudo rm -rf /Users/runner/.docker/machine/machines/default && s=$? && sleep 15; done; (exit $s)    # Retry 10 times before abort
+          
       - name: Export connection to Docker
         run: |
           DOCKER_TLS_VERIFY="$(docker-machine env default | grep DOCKER_TLS_VERIFY | sed -e 's/.*="//g' -e 's/"$//g')"
